name: Vercel-Auto-Deployment
on:
  push:
    branches: [ "main" ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Get Code
        uses: actions/checkout@v4

      - name: 🛠️ Setup Vercel
        run: npm install --global vercel@latest

      - name: 🚀 Deployment
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}